### ISSUE TITLE
Cannot run in docker

### ISSUE THREAD

**Issue by rty813** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#157]
After exec `meteor npm start`, it throws error as follow:

```
> semantic-segmentation-editor@1.6.0 start /root/semantic-segmentation-editor-1.6.0
> meteor run --settings settings.json --exclude-archs "web.browser.legacy, web.cordova"


You are attempting to run Meteor as the 'root' superuser. If you are developing, this is
almost certainly *not* what you want to do and will likely result in incorrect file
permissions. However, if you are running this command in a build process (CI, etc.), or
you are absolutely sure you know what you are doing, set the METEOR_ALLOW_SUPERUSER
environment variable or pass --allow-superuser to proceed.

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app directory
will be incorrect if you ever attempt to perform any Meteor tasks as a normal user. If
you need to fix your permissions, run the following command from the root of your
project:

  sudo chown -Rh <username> .meteor/local

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-segmentation-editor@1.6.0 start: `meteor run --settings settings.json --exclude-archs "web.browser.legacy, web.cordova"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-segmentation-editor@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-27T03_18_44_050Z-debug.log
```

-----
And the log content is as follewd
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
1 verbose cli   '/root/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle semantic-segmentation-editor@1.6.0~prestart: semantic-segmentation-editor@1.6.0
6 info lifecycle semantic-segmentation-editor@1.6.0~start: semantic-segmentation-editor@1.6.0
7 verbose lifecycle semantic-segmentation-editor@1.6.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle semantic-segmentation-editor@1.6.0~start: PATH: /root/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/semantic-segmentation-editor-1.6.0/node_modules/.bin:/root/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/root/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64:/root/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle semantic-segmentation-editor@1.6.0~start: CWD: /root/semantic-segmentation-editor-1.6.0
10 silly lifecycle semantic-segmentation-editor@1.6.0~start: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'meteor run --settings settings.json --exclude-archs "web.browser.legacy, web.cordova"'
10 silly lifecycle ]
11 silly lifecycle semantic-segmentation-editor@1.6.0~start: Returned: code: 1  signal: null
12 info lifecycle semantic-segmentation-editor@1.6.0~start: Failed to exec start script
13 verbose stack Error: semantic-segmentation-editor@1.6.0 start: `meteor run --settings settings.json --exclude-archs "web.browser.legacy, web.cordova"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/root/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid semantic-segmentation-editor@1.6.0
15 verbose cwd /root/semantic-segmentation-editor-1.6.0
16 verbose Linux 5.4.0-84-generic
17 verbose argv "/root/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/root/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "start"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error semantic-segmentation-editor@1.6.0 start: `meteor run --settings settings.json --exclude-archs "web.browser.legacy, web.cordova"`
22 error Exit status 1
23 error Failed at the semantic-segmentation-editor@1.6.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by hitbuyi** [comment]
I download a windows version of docker ,and can't run it in docker tooo, it prompts SSE_IMAGES and METEOR_SETTINGS are not set, in the windows version of docker, how to set thoese macros?
