### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by a873054267** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#178]
I had start the application on windows and mac operation system；but not on ubuntu
The environment：
1： Ubuntu 18.04.4
2： node version :13.14.0
 
I have deployed as documented，but can't start the application when I execute the commond ‘meteor npm start’；
the tips of terminal as follow：

Retrying after error Error: SQLITE_READONLY: attempt to write a readonly database
=> awaited here:
at Promise.await (/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
at Db._execute (/tools/packaging/catalog/catalog-remote.js:361:8)
at /tools/packaging/catalog/catalog-remote.js:150:10
at Db._retry (/tools/packaging/catalog/catalog-remote.js:162:16)
at new Db (/tools/packaging/catalog/catalog-remote.js:149:8)
at RemoteCatalog.initialize (/tools/packaging/catalog/catalog-remote.js:699:15)
at /tools/cli/main.js:875:20 {
errno: 8,
code: 'SQLITE_READONLY'
}

**Comment by a873054267** [comment]
it maybe the node version; use node 12.18.0 can run normally;
